version: "3.8"
services:
  camoufox:
    build:
      context: .
      dockerfile: Dockerfile.camoufox
    container_name: camoufox
    ports:
      - "7004:7004"
    volumes:
      - /data/camoufox:/app/logs
    networks:
      - shared-network
    restart: unless-stopped
networks:
  shared-network:
    external: true